### ISSUE TITLE
Save shots and shot number reporting seem to be broken

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#148]
I attach two .zip files. Both report a different number of shots in the `.aqn` file than in the .data file. Moreover in `Archive 2.zip` the `.aqn` file reports `save shots = True` but no shots seem to have been saved.
[Archive 2.zip](https://github.com/wright-group/PyCMDS/files/1496288/Archive.2.zip)
[Archive.zip](https://github.com/wright-group/PyCMDS/files/1496289/Archive.zip)

**Comment by untzag** [comment]
was this scan done through 'loading' or directly?

**Comment by darienmorrow** [comment]
I don't recall one way or the other. If I had to take a guess I would say _directly_. We should be able to test this on a lab machine...

**Comment by ksunden** [comment]
For save shots see #39

**Comment by ksunden** [comment]
https://github.com/wright-group/PyCMDS/blob/e34971d29bedfadbf2a17ba9ab1cef7be6aecd39/devices/PCI-6251/PCI-6251.py#L1000-L1003

Possibly related?

**Comment by ksunden** [comment]
Also possibly related to #99

**Comment by ksunden** [comment]
I now believe that the problem is because  the NI PCI-6251 class does not implement `get_headers` and thus it falls back to the base class version, which defines `self.nshots` which is never updated.

Can probably be solved by setting `self.nshots = nshots` in `__init__`, or by simply implementing `get_headers`

https://github.com/wright-group/PyCMDS/blob/9c262dc5ef4dce80cc4852e51887fee46c1332b7/devices/devices.py#L373-L377
