### ISSUE TITLE
DAQ parameterization 

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#16]
I believe that I have learned enough about *how* to address the DAQ for our purposes. The question now becomes how exactly we:

1. record samples from the DAQ 
2. process those raw samples into numbers that we record to data files
3. allow the user to make choices about how the above happens

It is important that we create a system that minimizes 'cross talk' and allows for digital background subtraction with more than one chopper. I personally want to create a system with the most transparent parameters as possible.

I have more thoughts but not much time at the moment. Just want to create a place for this discussion to happen right now.

**Comment by neffmallon** [comment]
Prescript: I don't really know what the vision for the format of data files is at this point. Do the data files contain a header that describes each of the columns and/or includes scan parameters, maybe instrument data like the monochromator used, etc.? I think we are going to need something like this, I'll assume it for this post.

0) For future reference, there are DAQ cards that can do simultaneous sampling (http://www.ni.com/datasheet/pdf/en/ds-151). I'm kicking myself for not getting one of those cards. :/

1) I'm a big fan of having a start and duration time for each channel, maybe with a text warning about how many points should be collected to minimize cross talk. A checkbox option for round robin sampling wouldn't be bad if it is desired. A graphic to show how the shots are allocated might be nice too. I liked the thing that Kent did where he showed all the collected data points over the sampling time and color coded them by channel. I'd consider that a nice bonus feature.

2&3) Normalization: I think we should include the ability to do shot-by-shot normalization. I don't really know how the DAQ works right now, how the data is transferred and manipulated by the computer, etc. It seems like since we can display every shot point on the screen that we can take those shot arrays and manipulate them directly in a aio0/(aio1*aio2) kind of way. As for user control, a simple "Normalize by" checklist could do the trick, something like this:
![image](https://cloud.githubusercontent.com/assets/13207223/9314240/48203fb2-44ed-11e5-84e8-666e6de69b68.png)

Photon counting for PMTs: This should include a sorting function. In addition to returning the average voltage over the specified number of shots, the program should, given two voltages, return the number of shots below the bottom voltage, between the two voltages, and above the top voltage. A cute fish (Poisson) distribution calculator determining the average number of photons per shot from this data would be great (and very very simple). Additional ability to normalize this to other inputs (like pyros) should also be possible.

PMT & Boxcar overvoltage warning: PMTs can short if they get too much light, but individual shots doing that isn't reflected in the average. It should be very clear to the user if this is happening. Flashing lights and sounds are appropriate. Also, if the voltage coming out of the boxcar is at the max for the boxcar, there should be similar warnings.

Very Simple Chopping: If there is only one chopper and the sign of the data isn't informative, then no output from the chopper is needed. The user could perhaps select from a checklist which aio channels are chopped and just return the absolute value of the difference of those channels.

Complicated Chopping: The phase of each chopper is selected from a carefully chosen point from the output of the chopper. Recognize the channels with the chopper inputs as choppers, allow the user to select an OPA beam line or omega number or other light source to associate with the chopper.  The raw (category averaged) data should be saved in columns with an appropriate binary header using a drop down menu (e.g. 011 for beam 0 off and beams 1 and 2 on or whatever). These categories can also be used as math (111 - 100 - 000 = data column) and saved as separate columns in the data file. This system hangs on to all the data, gives the user something to look at immediately, saves the processed data so it doesn't have to be re-calculated, etc. Again, it would be good to do shot-by-shot normalization with each of these additional "sub-channels." The nice thing about all of this is that the software doesn't need to know anything about the frequencies of the choppers or anything else, it uses only what it needs and gives the user everything they could want. Maybe the programmatic solution is to make virtual channel objects that can be treated like channels for data processing purposes but that are separate from the DAQ itself. Maybe there should be a chopper hardware object and these settings could be set up in the advanced tab of that hardware.

That is what I've thought of so far. What do you think?

**Comment by neffmallon** [comment]
Just remembered something else. Having a baseline corrected signal for time dependant signals like pyros and photodiodes would be nice. This would probably require a separate acquisition start time and duration. Maybe the way to do that would be to have two different virtual channel objects that take data from the same aio, but then math happens to give an output that the user wants, etc. Not committed to that idea at all, just throwing stuff out there.

**Comment by untzag** [comment]
I think we've agreed on how the DAQ should work in broad strokes. We can create individual issues if there are fine tuning features or bugs.
