### ISSUE TITLE
DAQ Thinks it is busy all the time

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#21]
Jonathan mentioned today that the DAQ thinks that it is busy most of the time, both in free-running mode and in module mode. We should look into this. I have no further details at this time.

**Comment by untzag** [comment]
We talked about it. It's because the trigger wasn't firing which basically crashed the DAQ. The DAQ does what I expect when the trigger is present.

I will admit that there is work to be done to make the DAQ more friendly during trigger loss, but that counts as feature addition rather than bug. I'm closing this.
