### ISSUE TITLE
3D Data is not being uploaded properly by Google Drive

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#55]
This has happened repeatedly over the last few days. I'm not sure what the cause is.

**Comment by untzag** [comment]
I believe I told you about this. It's a file size issue. Please upload manually. I have no idea how to fix it at this time. Apologies for my consistent failures.

**Comment by neffmallon** [comment]
Ok. I've got an idea. Is Google Drive already in its own thread? If so, we could just have a queue of files to transfer. Or we could only transfer the data files and not the images or something. Also, there was a past issue where this was partially resolved, right?

**Comment by untzag** [comment]
Google Drive is in its own thread, yes. It already works the way you describe. The images are not the problem since it goes file-by-file. The `.data` file is the only problem. I believe that there should be a `MemoryOverflow` error raised.

The frustrating thing is that file size should not cause problems. [PyDrive](https://pythonhosted.org/PyDrive/) claims to be able to use Google Drive's [streaming feature](https://developers.google.com/drive/v3/web/manage-uploads#resumable), so that the entire file is not loaded into memory at once. It seems like this feature may be broken in PyDrive itself. However at this time I would still guess that the problem is on my end.

There was a relatively recent change to how Google Drive works that made it more reliable, yes. However those changes did not address this issue.

**Comment by untzag** [comment]
See #41

**Comment by untzag** [comment]
@neffmallon is PyCMDS copying the files into the project/google_drive/temp folder? If so, you may consider using that folder as an easy place to find which files need to be manually uploaded.

**Comment by neffmallon** [comment]
Looks like pydrive was updated and fixed the memory error. I've updated PyDrive on the ps computer. As soon as I've tested it, I'll let you know, but it looks like it might be fixed.
